"""
Digest Generator

Generates weekly curiosity digests in various formats.
"""

from datetime import datetime
from typing import List, Optional
from pathlib import Path
import json


class DigestGenerator:
    """
    Generates formatted digests from curiosity signals.
    
    Output formats:
    - Markdown (for newsletter)
    - JSON (for API/database)
    - Social cards (for sharing)
    """
    
    TIER_EMOJIS = {
        "breakout": "🔥",
        "strong": "⭐",
        "signal": "📊",
        "noise": "📉",
    }
    
    def __init__(self, output_dir: str = "./output"):
        """
        Initialize generator.
        
        Args:
            output_dir: Directory for output files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_markdown(
        self,
        signals: List[dict],
        weird_picks: List[dict],
        week: str,
        stats: dict,
    ) -> str:
        """
        Generate a Markdown digest.
        
        Args:
            signals: Top signals for the week
            weird_picks: Weird/unexpected picks
            week: Week identifier (YYYY-WNN)
            stats: Pipeline statistics
            
        Returns:
            Markdown string
        """
        lines = []
        
        # Header
        lines.append(f"# What 10,000 Curious Minds Asked AI This Week")
        lines.append(f"### Week of {week}")
        lines.append("")
        lines.append(f"*{stats.get('questions_ingested', 0):,} questions analyzed across {stats.get('platforms', 2)} platforms*")
        lines.append("")
        
        # Top signals
        lines.append("---")
        lines.append("")
        lines.append("## 🎯 Top Signals This Week")
        lines.append("")
        
        for i, signal in enumerate(signals[:10], 1):
            emoji = self.TIER_EMOJIS.get(signal.get("tier", ""), "📈")
            velocity = signal.get("velocity_pct", 0)
            velocity_str = f"+{velocity:.0f}%" if velocity > 0 else f"{velocity:.0f}%"
            
            lines.append(f"### {i}. {emoji} {signal['question']}")
            lines.append("")
            
            # Stats row
            platforms = ", ".join(signal.get("platforms", []))
            lines.append(f"**{velocity_str}** velocity | **{signal.get('platform_count', 1)}** platforms ({platforms}) | **{signal.get('engagement', 0):,}** engagement")
            lines.append("")
            
            # News trigger if present
            news = signal.get("news_trigger")
            if news and news.get("headline"):
                lines.append(f"📰 *Triggered by: [{news['headline'][:60]}...]({news.get('url', '#')}) — {news.get('source', 'Unknown')}*")
                lines.append("")
            
            lines.append("")
        
        # Weird picks
        if weird_picks:
            lines.append("---")
            lines.append("")
            lines.append("## 🤔 Weird Picks")
            lines.append("*Questions that don't fit the pattern but caught our attention*")
            lines.append("")
            
            for pick in weird_picks[:3]:
                lines.append(f"- **{pick['question']}**")
            
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Curiosity Intelligence Engine*")
        lines.append(f"*Run: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")
        
        return "\n".join(lines)
    
    def generate_json(
        self,
        signals: List[dict],
        weird_picks: List[dict],
        week: str,
        stats: dict,
    ) -> dict:
        """
        Generate JSON export.
        """
        return {
            "week": week,
            "generated_at": datetime.utcnow().isoformat(),
            "stats": stats,
            "signals": signals,
            "weird_picks": weird_picks,
        }
    
    def save_digest(
        self,
        signals: List[dict],
        weird_picks: List[dict],
        week: str,
        stats: dict,
    ) -> dict:
        """
        Save digest in all formats.
        
        Returns:
            Dict with file paths
        """
        week_dir = self.output_dir / week.replace("-", "_")
        week_dir.mkdir(parents=True, exist_ok=True)
        
        # Markdown
        md_content = self.generate_markdown(signals, weird_picks, week, stats)
        md_path = week_dir / "digest.md"
        md_path.write_text(md_content)
        
        # JSON
        json_content = self.generate_json(signals, weird_picks, week, stats)
        json_path = week_dir / "digest.json"
        json_path.write_text(json.dumps(json_content, indent=2))
        
        # Individual signal files
        signals_dir = week_dir / "signals"
        signals_dir.mkdir(exist_ok=True)
        
        for i, signal in enumerate(signals, 1):
            signal_path = signals_dir / f"signal_{i:02d}.json"
            signal_path.write_text(json.dumps(signal, indent=2))
        
        return {
            "markdown": str(md_path),
            "json": str(json_path),
            "signals_dir": str(signals_dir),
        }
    
    def generate_social_card(
        self,
        signal: dict,
        week: str,
    ) -> Optional[str]:
        """
        Generate a social media card for a signal.
        
        Returns path to generated image.
        """
        # Placeholder - would use PIL/Pillow to generate image
        # For now, just return a text template
        return f"""
┌────────────────────────────────────────────┐
│  🧠 CURIOSITY SIGNAL                       │
│                                            │
│  "{signal['question'][:40]}..."            │
│                                            │
│  {self.TIER_EMOJIS.get(signal.get('tier', ''))} {signal.get('tier', '').upper()}  |  {signal.get('velocity_pct', 0):+.0f}% velocity │
│                                            │
│  Week {week}                               │
└────────────────────────────────────────────┘
        """.strip()
